# Thébault's first problem — the centers of squares erected on the sides of a parallelogram form a square (source: Thébault 1937)
A B C = triangle
D = parallelogram(A, B, C)
P1 Q1 = square(A, B)
P2 Q2 = square(B, C)
P3 Q3 = square(C, D)
P4 Q4 = square(D, A)
O1 = midpoint(A, P1)
O2 = midpoint(B, P2)
O3 = midpoint(C, P3)
O4 = midpoint(D, P4)
prove perp(O1, O3, O2, O4)
